//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.CrossCutting.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برقم (.
        /// </summary>
        internal static string @__number {
            get {
                return ResourceManager.GetString(") number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string addition {
            get {
                return ResourceManager.GetString("addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إذن الإضافة:.
        /// </summary>
        internal static string AdditionDate {
            get {
                return ResourceManager.GetString("AdditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم إذن الإضافة:.
        /// </summary>
        internal static string AdditionNumber {
            get {
                return ResourceManager.GetString("AdditionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرتجاع كل الأصناف في هذا الإيصال.
        /// </summary>
        internal static string AllItemsInInvoiceAreRefunded {
            get {
                return ResourceManager.GetString("AllItemsInInvoiceAreRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاح.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود.
        /// </summary>
        internal static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و ذلك علي مقتضي العقد الموقع مع.
        /// </summary>
        internal static string Based_on_the_contract_with {
            get {
                return ResourceManager.GetString("Based on the contract with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و ذلك علي مقتضي أمر التوريد الصادر إلي.
        /// </summary>
        internal static string Based_on_the_supply_order_to {
            get {
                return ResourceManager.GetString("Based on the supply order to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الصنف :.
        /// </summary>
        internal static string BaseItemCode {
            get {
                return ResourceManager.GetString("BaseItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة المستلم منها الصنف:.
        /// </summary>
        internal static string BaseItemDepartment {
            get {
                return ResourceManager.GetString("BaseItemDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الدفتر :.
        /// </summary>
        internal static string BookType {
            get {
                return ResourceManager.GetString("BookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموازنة:.
        /// </summary>
        internal static string BudgetName {
            get {
                return ResourceManager.GetString("BudgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الغاء.
        /// </summary>
        internal static string cancalorder {
            get {
                return ResourceManager.GetString("cancalorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الغاء محضر الاعدام حيث ان حالة محضر الاعدام ليست قيد الانتظار.
        /// </summary>
        internal static string CanceledExecutionOrder {
            get {
                return ResourceManager.GetString("CanceledExecutionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير حالة امر التكهين.
        /// </summary>
        internal static string CanceledRobbingOrder {
            get {
                return ResourceManager.GetString("CanceledRobbingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير حالة امر النقل.
        /// </summary>
        internal static string CanceledTransformation {
            get {
                return ResourceManager.GetString("CanceledTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن تعديل هذا الصنف حيث أنه مرتبط بموجودات في المخزن.
        /// </summary>
        internal static string CanNotEditBaseItem {
            get {
                return ResourceManager.GetString("CanNotEditBaseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الكارنيه موجود من قبل.
        /// </summary>
        internal static string CardCodeExist {
            get {
                return ResourceManager.GetString("CardCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا تم تغيير حالة امر الصرف.
        /// </summary>
        internal static string ChangeReviewExchangeorder {
            get {
                return ResourceManager.GetString("ChangeReviewExchangeorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تم تغيير حالة  امر الارتجاع.
        /// </summary>
        internal static string ChangeReviewRefund {
            get {
                return ResourceManager.GetString("ChangeReviewRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفويض المستخدم من قبل.
        /// </summary>
        internal static string checkDelegationTechnican {
            get {
                return ResourceManager.GetString("checkDelegationTechnican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود :  .
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستهلك.
        /// </summary>
        internal static string Consumed {
            get {
                return ResourceManager.GetString("Consumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ صدور العقد:.
        /// </summary>
        internal static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العقد:.
        /// </summary>
        internal static string ContractNum {
            get {
                return ResourceManager.GetString("ContractNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء.
        /// </summary>
        internal static string createOrder {
            get {
                return ResourceManager.GetString("createOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عهدة.
        /// </summary>
        internal static string Custody {
            get {
                return ResourceManager.GetString("Custody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التفويض.
        /// </summary>
        internal static string DelegationDate {
            get {
                return ResourceManager.GetString("DelegationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ عملية التفويض.
        /// </summary>
        internal static string DelegationTrackDate {
            get {
                return ResourceManager.GetString("DelegationTrackDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة :.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوف يتم التعديل بنجاح.
        /// </summary>
        internal static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الموظف :.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الموظف موجود.
        /// </summary>
        internal static string EmployeeNameExist {
            get {
                return ResourceManager.GetString("EmployeeNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ محضر لجنة الفحص:.
        /// </summary>
        internal static string ExaminationDate {
            get {
                return ResourceManager.GetString("ExaminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم محضر لجنة الفحص:.
        /// </summary>
        internal static string ExaminationNum {
            get {
                return ResourceManager.GetString("ExaminationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة محضر الفحص:.
        /// </summary>
        internal static string ExaminationStatus {
            get {
                return ResourceManager.GetString("ExaminationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صرف.
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الصرف.
        /// </summary>
        internal static string ExchangeOrder {
            get {
                return ResourceManager.GetString("ExchangeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ أمر الصرف:.
        /// </summary>
        internal static string ExchangeOrderDate {
            get {
                return ResourceManager.GetString("ExchangeOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم أمر الصرف:.
        /// </summary>
        internal static string ExchangeOrderNumber {
            get {
                return ResourceManager.GetString("ExchangeOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة أمر الصرف:.
        /// </summary>
        internal static string ExchangeOrderStatus {
            get {
                return ResourceManager.GetString("ExchangeOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصروف إلى:.
        /// </summary>
        internal static string ExchangeOrderTo {
            get {
                return ResourceManager.GetString("ExchangeOrderTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاعدام.
        /// </summary>
        internal static string ExecutionOrder {
            get {
                return ResourceManager.GetString("ExecutionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ طلب الإعدام :.
        /// </summary>
        internal static string ExecutionOrderDate {
            get {
                return ResourceManager.GetString("ExecutionOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم طلب الإعدام :.
        /// </summary>
        internal static string ExecutionOrderNumber {
            get {
                return ResourceManager.GetString("ExecutionOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة طلب الإعدام :.
        /// </summary>
        internal static string ExecutionOrderStatus {
            get {
                return ResourceManager.GetString("ExecutionOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة الخارجية :.
        /// </summary>
        internal static string ExternalEntity {
            get {
                return ResourceManager.GetString("ExternalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من المورد.
        /// </summary>
        internal static string From_supplier {
            get {
                return ResourceManager.GetString("From supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في الخادم الداخلي.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الإذن مستخدم بالفعل. برجاء إختيار رقم آخر.
        /// </summary>
        internal static string InvalidAdditionNumber {
            get {
                return ResourceManager.GetString("InvalidAdditionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل هذا الدفتر لأنه مربوط بأصناف فى مخزن .
        /// </summary>
        internal static string invalidBookEdit {
            get {
                return ResourceManager.GetString("invalidBookEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة هذا الدفتر لهذا المخزن من قبل.
        /// </summary>
        internal static string InvalidBookException {
            get {
                return ResourceManager.GetString("InvalidBookException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن إلغاء أمر الصرف حيث ان حالته ليست قيد الانتظار.
        /// </summary>
        internal static string InvalidCanceledExchangeOrder {
            get {
                return ResourceManager.GetString("InvalidCanceledExchangeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن إلغاء أمر الارتجاع حيث ان حالته ليست قيد الانتظار.
        /// </summary>
        internal static string InvalidCanceledRefundOrder {
            get {
                return ResourceManager.GetString("InvalidCanceledRefundOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يسمح بإلغاء تفعيل هذا العنصر لوجوده فى قوائم اخرى.
        /// </summary>
        internal static string InvalidDeactivation {
            get {
                return ResourceManager.GetString("InvalidDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل الموازنة.الأصناف المضافة تم ربطها بأوامر صرف.
        /// </summary>
        internal static string InvalidEditExaminationBudget {
            get {
                return ResourceManager.GetString("InvalidEditExaminationBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات غير صحيحة.
        /// </summary>
        internal static string InvalidException {
            get {
                return ResourceManager.GetString("InvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعض الحقول مطلوبة.
        /// </summary>
        internal static string InvalidModelStateException {
            get {
                return ResourceManager.GetString("InvalidModelStateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إرجاع الأصناف الموجودة في أمر الارتجاع لأنه تم إلغائه.
        /// </summary>
        internal static string InvalidRefundOrder {
            get {
                return ResourceManager.GetString("InvalidRefundOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ حالة الأصناف مختلفة عن الحالة التى تم عرض البيانات بها .
        /// </summary>
        internal static string InvalidStoreItemStatusException {
            get {
                return ResourceManager.GetString("InvalidStoreItemStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او كلمة السر غير صحيحة.
        /// </summary>
        internal static string InvalidUserNameOrPasswordException {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إيصال الاستلام:.
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيصال الاستلام لا يوجد به أي أصناف.
        /// </summary>
        internal static string InvoiceHasNoItems {
            get {
                return ResourceManager.GetString("InvoiceHasNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم إيصال الاستلام:.
        /// </summary>
        internal static string InvoiceNum {
            get {
                return ResourceManager.GetString("InvoiceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بتاريخ.
        /// </summary>
        internal static string issued_on {
            get {
                return ResourceManager.GetString("issued on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة الصنف : .
        /// </summary>
        internal static string ItemCategory {
            get {
                return ResourceManager.GetString("ItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الصنف :.
        /// </summary>
        internal static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصنف :.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الصنف :.
        /// </summary>
        internal static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة :.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكان :.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يسمح بوجود اكتر من مخزن للإدارة الفنية.
        /// </summary>
        internal static string MoreeThanOneException {
            get {
                return ResourceManager.GetString("MoreeThanOneException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يسمح بوجود اكتر من مخزن كهمة للموازنة الواحدة.
        /// </summary>
        internal static string MoreThanOneStorePerBudgetException {
            get {
                return ResourceManager.GetString("MoreThanOneStorePerBudgetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار صنف للطباعة.
        /// </summary>
        internal static string MustSelectBaseItemId {
            get {
                return ResourceManager.GetString("MustSelectBaseItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار اسم المستلم.
        /// </summary>
        internal static string MustSelectReciever {
            get {
                return ResourceManager.GetString("MustSelectReciever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل فى أى من البيانات .
        /// </summary>
        internal static string NoChangesInEdit {
            get {
                return ResourceManager.GetString("NoChangesInEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد بيانات للطباعة حيث أن الصنف لم يتم صرفه.
        /// </summary>
        internal static string NoDataAsNoExchange {
            get {
                return ResourceManager.GetString("NoDataAsNoExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات للطباعة.
        /// </summary>
        internal static string NoDataException {
            get {
                return ResourceManager.GetString("NoDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاتوجد بيانات تطابق معايير البحث.
        /// </summary>
        internal static string NoDataExist {
            get {
                return ResourceManager.GetString("NoDataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مفعل.
        /// </summary>
        internal static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستديم.
        /// </summary>
        internal static string NotConsumed {
            get {
                return ResourceManager.GetString("NotConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أختيار مخزن على الاقل.
        /// </summary>
        internal static string NotDelegationStores {
            get {
                return ResourceManager.GetString("NotDelegationStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إلغاء الصنف حيث تم إضافة أوامر صرف علية.
        /// </summary>
        internal static string NotdeleteItem {
            get {
                return ResourceManager.GetString("NotdeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إلغاء الصنف حيث تم إضافته لأوامر تكهين.
        /// </summary>
        internal static string NotdeleteItemRobbing {
            get {
                return ResourceManager.GetString("NotdeleteItemRobbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف الصنف حيث تم إضافة  طلبات نقل عهدة او طلبات تكهين او طلبات إعدام.
        /// </summary>
        internal static string NotDeletetemOperation {
            get {
                return ResourceManager.GetString("NotDeletetemOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ البيانات.
        /// </summary>
        internal static string NotSavedException {
            get {
                return ResourceManager.GetString("NotSavedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل الصنف حيث تم إضافة أوامر صرف علية.
        /// </summary>
        internal static string NotUpdateItem {
            get {
                return ResourceManager.GetString("NotUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل الصنف حيث تم إضافة  طلبات نقل عهدة او طلبات تكهين او طلبات إعدام.
        /// </summary>
        internal static string NotUpdateItemOperation {
            get {
                return ResourceManager.GetString("NotUpdateItemOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل الصنف حيث تم إضافته لأوامر التكهين.
        /// </summary>
        internal static string NotUpdateItemRobbing {
            get {
                return ResourceManager.GetString("NotUpdateItemRobbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم غير مسموح له بالدخول على هذا المخزن.
        /// </summary>
        internal static string NotValidTenant {
            get {
                return ResourceManager.GetString("NotValidTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال مصطلح للبحث .
        /// </summary>
        internal static string NullSearchValueException {
            get {
                return ResourceManager.GetString("NullSearchValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )  بتاريخ.
        /// </summary>
        internal static string on__ {
            get {
                return ResourceManager.GetString("on (", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الصفحة :.
        /// </summary>
        internal static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة التابع لها المستلم:.
        /// </summary>
        internal static string ReceivedDepartment {
            get {
                return ResourceManager.GetString("ReceivedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصروف إلى:.
        /// </summary>
        internal static string ReceivedEmployee {
            get {
                return ResourceManager.GetString("ReceivedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستلم:.
        /// </summary>
        internal static string RecieverName {
            get {
                return ResourceManager.GetString("RecieverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ أمر الارتجاع:.
        /// </summary>
        internal static string RefundDate {
            get {
                return ResourceManager.GetString("RefundDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم أمر الارتجاع:.
        /// </summary>
        internal static string RefundNum {
            get {
                return ResourceManager.GetString("RefundNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الارتجاع.
        /// </summary>
        internal static string refundorder {
            get {
                return ResourceManager.GetString("refundorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أمر الارتجاع لا يوجد به أي أصناف تالفة.
        /// </summary>
        internal static string RefundOrderHasNoTaintedItems {
            get {
                return ResourceManager.GetString("RefundOrderHasNoTaintedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البقايا :.
        /// </summary>
        internal static string Remains {
            get {
                return ResourceManager.GetString("Remains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البقايا موجود من قبل.
        /// </summary>
        internal static string RemainsNameAlreadyExist {
            get {
                return ResourceManager.GetString("RemainsNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل الصنف حيث تم إضافة  طلبات نقل عهدة او طلبات تكهين او طلبات إعدام  او اوامر الصرف.
        /// </summary>
        internal static string ResultStoreItem {
            get {
                return ResourceManager.GetString("ResultStoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن مراجعة محضر الإعدام حيث أن حالة محضر الإعدام ليست قيد الانتظار.
        /// </summary>
        internal static string ReviewedExecutionOrder {
            get {
                return ResourceManager.GetString("ReviewedExecutionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم مراجعة.
        /// </summary>
        internal static string reviewOrder {
            get {
                return ResourceManager.GetString("reviewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كهنة.
        /// </summary>
        internal static string robbing {
            get {
                return ResourceManager.GetString("robbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ أمر التكهين :.
        /// </summary>
        internal static string RobbingDate {
            get {
                return ResourceManager.GetString("RobbingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم أمر التكهين :.
        /// </summary>
        internal static string RobbingNum {
            get {
                return ResourceManager.GetString("RobbingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الطلب تم إضافته من قبل.
        /// </summary>
        internal static string robbingOrderAddedBefore {
            get {
                return ResourceManager.GetString("robbingOrderAddedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الإضافة حيث تم إلغاء أمر التكهين.
        /// </summary>
        internal static string RobbingRequestCanselBefore {
            get {
                return ResourceManager.GetString("RobbingRequestCanselBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم محضر الجرد:.
        /// </summary>
        internal static string StockTakingCode {
            get {
                return ResourceManager.GetString("StockTakingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ محضر الجرد:.
        /// </summary>
        internal static string StockTakingDate {
            get {
                return ResourceManager.GetString("StockTakingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انتهاء وقت التفويض بالفعل.
        /// </summary>
        internal static string StopDelegationError {
            get {
                return ResourceManager.GetString("StopDelegationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخزن.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخزن :.
        /// </summary>
        internal static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع :.
        /// </summary>
        internal static string StoreType {
            get {
                return ResourceManager.GetString("StoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الإذن : .
        /// </summary>
        internal static string SubtractionNumber {
            get {
                return ResourceManager.GetString("SubtractionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة التوريد:.
        /// </summary>
        internal static string SuppliedTo {
            get {
                return ResourceManager.GetString("SuppliedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد :.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة الفنية :.
        /// </summary>
        internal static string TechnicalDepartment {
            get {
                return ResourceManager.GetString("TechnicalDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإضافة.
        /// </summary>
        internal static string the_addition {
            get {
                return ResourceManager.GetString("the addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصرف.
        /// </summary>
        internal static string TheExchange {
            get {
                return ResourceManager.GetString("TheExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم طلب نقل العهدة:.
        /// </summary>
        internal static string TransformationNumber {
            get {
                return ResourceManager.GetString("TransformationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الطلب تم إضافته من قبل.
        /// </summary>
        internal static string transformationRequestAddedBefore {
            get {
                return ResourceManager.GetString("transformationRequestAddedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الإضافة حيث تم إلغاء أمر نقل العهدة.
        /// </summary>
        internal static string transformationRequestCanselBefore {
            get {
                return ResourceManager.GetString("transformationRequestCanselBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ طلب نقل العهدة:.
        /// </summary>
        internal static string TransformationRequestDate {
            get {
                return ResourceManager.GetString("TransformationRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم غير مسموح له باستخدام النظام.
        /// </summary>
        internal static string UnAuthorizedException {
            get {
                return ResourceManager.GetString("UnAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة : .
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم ليس له مخازن للعمل عليها.
        /// </summary>
        internal static string UserHasNoTenantException {
            get {
                return ResourceManager.GetString("UserHasNoTenantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم غير موجود.
        /// </summary>
        internal static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
    }
}
